name: HamsterSystem
main: com.github.schooluniform.hamstersystem.HamsterSystem
version: 0.0.1
author: School_Uniform
commands:
  hs:
    description: getHamsterSystemHelp
    usage: /<command> help
  HamsterSystem:
    description: getHamsterSystemHelp
    usage: /<command> help
permissions: 
  HamsterSystem.Admin: 
    description: Use commands
    default: op